### PR TITLE
added carrier IP to android and ios

### PR DESCRIPTION
**Pull request by winfinit**
added ability to get carriers IP

### CODE REVIEW

**Comment by winfinit** [comment]
there is ionic 2 demo app that can be used to demo this functionality:
https://github.com/winfinit/ionic2-demo-cordova-plugin-networkinterface

**Comment by salbahra** [comment]
Can we keep the old `getIPAddress` method in place which just uses `getWiFiAddress` instead of breaking support for the previous method?

**Comment by salbahra** [comment]
Not sure if the commit I made was done to your actual master branch (not sure why I am allowed to do that), sorry. However, I think that simple fix is all that's needed to make this a good solution moving forward.

**Comment by salbahra** [comment]
Ah awesome! Okay I think we can merge this in then, I see no issues.

**Pull request merged**
